contacts/urls.py
""" STANDARD DJANGO IMPORTS """

from django.urls import path

""" LOCAL APP IMPORTS """

from .views import (
    create_view,
    delete_view,
    edit_view,
    not_found_view,
    toggle_favourite,
    unauthorized_view,
)


app_name = "contacts"

urlpatterns = [
    path("create/", create_view, name="create"),
    path("<int:pk>/edit", edit_view, name="edit"),
    path("<int:pk>/delete", delete_view, name="delete"),
    path("<int:pk>/toggle-favourite", toggle_favourite, name="toggle-favourite"),
    path("unauthorized/", unauthorized_view, name="unauthorized"),
    path("not-found/", not_found_view, name="not-found"),
]

main/urls.py
""" STANDARD DJANGO IMPORTS """

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path("", include("accounts.urls")),
    path("contacts/", include("contacts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/401.html
{% extends 'base.html' %}

{% block title %} 401 {% endblock %}

{% block content %}
<div class="mx-auto text-center">
    <h1 class="text-5xl">401.</h1>
    <h3 class="text-2xl">You're not authorized to view this page.</h3>
    <p>
        Try going back to
        <a href="{% url 'home' %}" class="text-purple-700 font-semibold">Home page.</a>
    </p>
</div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<title>{% block title %} Contact Manager - Powered by Django {% endblock %}</title>
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;600;700&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">
	<script src="{% static 'assets/js/tailwind.cdn.js' %}"></script>
</head>

<body class="relative flex flex-col items-center min-h-screen bg-zinc-100">
	{% include 'navbar.html' %}
	<main class="mt-5 flex flex-1 flex-col w-3/4">
		{% block content %}{% endblock %}
		<div class="mx-auto mt-3">
			{% include 'messages.html' %}
		</div>
	</main>
	{% include 'footer.html' %}

	<!-- EXTRA JS -->
	{% block js %}{% endblock %}
</body>

</html>

templates/credits.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}

<div class="mx-auto text-center">
    <h3 class="text-2xl mb-10">This project uses following stuff:</h3>
    <ul>
        {% for link in links %}
        <li class="text-sm">
            {{ link.category }}:
            <a href="{{ link.url }}" target="_blank" rel="noopener noreferrer" class="text-purple-700 font-semibold">
                {{ link.caption }}
            </a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

templates/footer.html
<footer class="p-3 text-sm">
    <p>
        &copy;
        <a href="https://github.com/ahmadgirach/dj-contact-manager" target="_blank" rel="noopener noreferrer"
            class="text-purple-700 font-semibold">
            Ahmad Girach
        </a>
    </p>
</footer>

templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Home {% endblock %}

{% block content %}
<div class="space-y-10">
    <!-- <h3 class="text-2xl text-center">Contacts</h3> -->

    <form action="{% url 'home' %}" method="get">
        <div class="flex justify-center items-center gap-5">
            <label for="search" class="mb-2 text-sm font-medium text-gray-900 sr-only">Search</label>
            <div class="relative w-1/3">
                <input type="search" id="search" name="search"
                    class="block w-full p-4 text-sm text-gray-900 border border-gray-300 rounded-lg bg-purple-50"
                    placeholder="Search Contacts..." required>
                <button type="submit"
                    class="text-white absolute right-2.5 bottom-2.5 bg-purple-700 hover:bg-purple-800 focus:ring-4 focus:outline-none focus:ring-purple-300 font-medium rounded-lg text-sm px-4 py-2">
                    <svg aria-hidden="true" class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                        xmlns="http://www.w3.org/2000/svg">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                    </svg>
                </button>
            </div>
            <a href="{% url 'home' %}" class="text-sm underline">Clear Filters</a>
            <a href="{% url 'contacts:create' %}"
                class="text-white bg-purple-700 hover:bg-purple-800 focus:ring-4 focus:outline-none focus:ring-purple-300 font-semibold rounded-lg text-sm text-center p-2 md:px-4 md:py-2">
                + Add New Contact
            </a>
        </div>
    </form>

    <div class="overflow-x-auto relative shadow-md sm:rounded-lg">
        <table class="w-full text-sm text-left text-gray-500 ">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50  ">
                <tr>
                    <th scope="col" class="py-3 px-6">
                        Name
                    </th>
                    <th scope="col" class="py-3 px-6">
                        Phone Number
                    </th>
                    <th scope="col" class="py-3 px-6">
                        Organization
                    </th>
                    <th scope="col" class="py-3 px-6">
                        Action
                    </th>
                </tr>
            </thead>
            <tbody>
                {{ contacts }}
                {% if page_obj.object_list %}
                {% for contact in page_obj.object_list %}
                {% with fav=contact.is_favourite %}
                <tr class="bg-white border-b hover:bg-gray-50">
                    <th scope="row" class="flex items-center py-4 px-6 text-gray-900 whitespace-nowrap">
                        <img class="w-12 h-12 rounded-full"
                            src="{% if contact.avatar %} {{ contact.avatar.url }} {% else %} {% static 'assets/images/user.svg' %} {% endif %}"
                            alt="Contact Avatar">
                        <div class="pl-3">
                            <div class="text-base font-semibold">{{ contact.get_full_name }}</div>
                            <div class="font-normal text-gray-600">
                                {% if contact.email %} {{ contact.email }} {% else %} - {% endif %}
                            </div>
                        </div>
                    </th>
                    <td class="py-4 px-6">
                        {% if contact.phone_number %} {{ contact.phone_number }} {% else %} - {% endif %}
                    </td>
                    <td class="py-4 px-6">
                        {% if contact.organization %} {{ contact.organization }} {% else %} - {% endif %}
                    </td>
                    <td class="py-4 px-6">
                        <a href="{% url 'contacts:edit' contact.pk %}" title="Edit Contact">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                                stroke="currentColor" class="w-5 h-5 inline-block">
                                <path stroke-linecap="round" stroke-linejoin="round"
                                    d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
                            </svg>
                        </a>
                        <a onclick="handleDelete(event, '{{ contact.pk }}')" class="cursor-pointer"
                            title="Delete Contact">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                                stroke="currentColor" class="w-5 h-5 inline-block">
                                <path stroke-linecap="round" stroke-linejoin="round"
                                    d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
                            </svg>
                        </a>
                        <a onclick="toggleFavourite(event, '{{ contact.pk }}', '{{ fav }}')" class="cursor-pointer"
                            title="{% if fav %} Remove from Favourites? {% else %} Mark as Favourite? {% endif %}">
                            {% if fav %}
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"
                                class="w-6 h-6 inline-block">
                                <path fill-rule="evenodd"
                                    d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.006z"
                                    clip-rule="evenodd" />
                            </svg>
                            {% else %}
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                                stroke="currentColor" class="w-6 h-6 inline-block">
                                <path stroke-linecap="round" stroke-linejoin="round"
                                    d="M11.48 3.499a.562.562 0 011.04 0l2.125 5.111a.563.563 0 00.475.345l5.518.442c.499.04.701.663.321.988l-4.204 3.602a.563.563 0 00-.182.557l1.285 5.385a.562.562 0 01-.84.61l-4.725-2.885a.563.563 0 00-.586 0L6.982 20.54a.562.562 0 01-.84-.61l1.285-5.386a.562.562 0 00-.182-.557l-4.204-3.602a.563.563 0 01.321-.988l5.518-.442a.563.563 0 00.475-.345L11.48 3.5z" />
                            </svg>
                            {% endif %}
                        </a>
                    </td>
                </tr>
                {% endwith %}
                {% endfor %}
                {% else %}
                <tr class="bg-white border-b hover:bg-gray-50">
                    <td colspan="4" class="py-4 px-6">No contacts found.</td>
                </tr>
                {% endif %}
            </tbody>
        </table>

        <!-- PAGINATION -->
        <!-- IF THERE'S ONLY 1 PAGE, DON'T SHOW THESE BUTTONS. -->
        {% if show_pagination %}
        <ul class="flex justify-center items-center p-3 text-sm">
            {% if page_obj.has_previous %}
            <li>
                <a href="?page={{ page_obj.previous_page_number }}"
                    class="block px-3 py-2 ml-0 leading-tight text-gray-500 bg-white border border-gray-300 rounded-l-lg hover:bg-gray-100 hover:text-gray-700">
                    <span class="sr-only">Previous</span>
                    <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20"
                        xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z"
                            clip-rule="evenodd"></path>
                    </svg>
                </a>
            </li>
            {% endif %}

            {% for page in no_of_pages_range %}
            <li>
                <a href="?page={{ page }}"
                    class="px-3 py-2 leading-tight border border-purple-300 {% if page_obj.number == page %} text-white bg-purple-800 hover:bg-purple-900 hover:text-gray-50 {% else %} text-gray-500 bg-white hover:bg-gray-100 hover:text-gray-700 {% endif %}">
                    {{ page }}
                </a>
            </li>
            {% endfor %}

            {% if page_obj.has_next %}
            <li>
                <a href="?page={{ page_obj.next_page_number }}"
                    class="block px-3 py-2 leading-tight text-gray-500 bg-white border border-gray-300 rounded-r-lg hover:bg-gray-100 hover:text-gray-700">
                    <span class="sr-only">Next</span>
                    <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20"
                        xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                            clip-rule="evenodd"></path>
                    </svg>
                </a>
            </li>
            {% endif %}
        </ul>
        {% endif %}
    </div>

    <!-- INDICATATES THAT PAGINATION IS ACTIVE. -->
    {% if not show_pagination %}
    <p class="text-sm text-center my-5">Page 1 of 1</p>
    {% endif %}
</div>
{% endblock %}

{% block js %}
<script src="{% static 'assets/js/sweetalert2.min.js' %}"></script>
<script>
    function handleDelete(e, pk) {
        e.preventDefault();
        Swal.fire({
            title: "Are you sure?",
            text: "You won't be able to revert this!",
            icon: "warning",
            showCancelButton: true,
            confirmButtonColor: "#d33",
            confirmButtonText: "Yes, delete it!"
        }).then(async (result) => {
            if (result.isConfirmed) {
                const cookies = document.cookie;
                const [key, value] = cookies.split("=");
                const url = `/contacts/${pk}/delete`;
                const response = await fetch(
                    url,
                    {
                        method: "POST",
                        headers: {
                            "X-CSRFToken": value
                        },
                    },
                );
                if (response.status === 200) {
                    window.location.reload();
                } else {
                    Swal.fire("Oops!", "Something went wrong while deleting the contact!", "error");
                }
            }
        });
    }

    function toggleFavourite(e, pk, favourite) {
        e.preventDefault();
        const text = favourite === "True" ? "This contact will be removed from your favourites!" : "This contact will be added to your favourites!";
        Swal.fire({
            title: "Are you sure?",
            text,
            icon: "question",
            showCancelButton: true,
            confirmButtonText: "Yes, do it!"
        }).then(async (result) => {
            if (result.isConfirmed) {
                const cookies = document.cookie;
                const [key, value] = cookies.split("=");
                const url = `/contacts/${pk}/toggle-favourite`;
                const response = await fetch(
                    url,
                    {
                        method: "POST",
                        headers: {
                            "X-CSRFToken": value
                        },
                    },
                );
                if (response.status === 200) {
                    window.location.reload();
                } else {
                    Swal.fire("Oops!", "Something went wrong while marking the contact as favourite!", "error");
                }
            }
        });
    }
</script>
{% endblock %}

templates/messages.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }} text-red-700" {% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

templates/navbar.html
<header class="bg-purple-700 text-white w-full p-2">
    <nav class="flex flex-col md:flex-row justify-between items-center gap-2 px-10">
        <a href="{% url 'home' %}" class="font-bold">ContactManager</a>
        <ul class="flex justify-center items-center gap-3 uppercase text-sm font-semibold">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'credits' %}">Credits</a></li>
        </ul>
        <div class="md:py-2 space-x-3">
            {% if not user.is_authenticated %}
            <a href="{% url 'signup' %}"
                class="px-2 py-1 md:px-3 md:py-2 bg-white text-purple-800 hover:bg-purple-800 hover:text-white transition font-semibold rounded-md uppercase text-sm">
                Sign Up
            </a>
            <a href="{% url 'signin' %}"
                class="px-2 py-1 md:px-3 md:py-2 bg-white text-purple-800 hover:bg-purple-800 hover:text-white transition font-semibold rounded-md uppercase text-sm">
                Sign In
            </a>
            {% else %}
            <!-- <span class="text-sm font-semibold">Welcome {{ user.get_full_name }},</span> -->
            <a href="{% url 'logout' %}" class="uppercase font-semibold text-sm">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                    stroke="currentColor" class="w-6 h-6 inline-block">
                    <path stroke-linecap="round" stroke-linejoin="round"
                        d="M15.75 9V5.25A2.25 2.25 0 0013.5 3h-6a2.25 2.25 0 00-2.25 2.25v13.5A2.25 2.25 0 007.5 21h6a2.25 2.25 0 002.25-2.25V15M12 9l-3 3m0 0l3 3m-3-3h12.75" />
                </svg>
                Logout
            </a>
            {% endif %}
        </div>
    </nav>
</header>